import "./globals.css";
import TopBanner from "./TopBanner";

export const metadata = {
  title: "My Kind Of Cruise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBanner />
        {children}
      </body>
    </html>
  );
}
